import { useEffect, useRef, useState } from 'react'
import { siteConfig, type Project } from './config'

const sections = [{ id: 'work', label: 'Work' }, { id: 'skills', label: 'Skills' }, { id: 'approach', label: 'Approach' }, { id: 'contact', label: 'Contact' }]
const categories = ['All', 'Backend/APIs', 'Frontend', 'Cloud/DevOps', 'CMS/content', 'Data/integrations', 'AI/automation'] as const

function App() {
  const [dark, setDark] = useState(true); const [menu, setMenu] = useState(false)
  const [category, setCategory] = useState<(typeof categories)[number]>('All')
  const [visibleProjects, setVisibleProjects] = useState(5); const [selected, setSelected] = useState<Project | null>(null)
  const [active, setActive] = useState('work'); const menuButton = useRef<HTMLButtonElement>(null); const modalRef = useRef<HTMLElement>(null)
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light' }, [dark])
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-25% 0px -65% 0px' })
    sections.forEach(({ id }) => { const element = document.getElementById(id); if (element) observer.observe(element) }); return () => observer.disconnect()
  }, [])
  useEffect(() => {
    if (!selected) return
    const previous = document.activeElement as HTMLElement; modalRef.current?.focus()
    const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setSelected(null) }
    document.addEventListener('keydown', onKey); return () => { document.removeEventListener('keydown', onKey); previous?.focus() }
  }, [selected])
  const closeMenu = () => { setMenu(false); menuButton.current?.focus() }
  const skills = siteConfig.skills.filter((skill) => category === 'All' || skill.category === category)
  return <div className="site-shell">
    <header className="nav-wrap"><nav className="nav" aria-label="Main navigation">
      <a className="brand" href="#top" aria-label="Home"><span className="brand-mark">EI</span><span>Engineering<br /><b>Intelligence</b></span></a>
      <button ref={menuButton} className="menu-button" aria-expanded={menu} aria-controls="nav-links" onClick={() => setMenu(!menu)} onKeyDown={(e) => e.key === 'Escape' && closeMenu()}><span>{menu ? 'Close' : 'Menu'}</span><i /></button>
      <div id="nav-links" className={`nav-links ${menu ? 'is-open' : ''}`}>{sections.map((item) => <a className={active === item.id ? 'current' : ''} aria-current={active === item.id ? 'page' : undefined} key={item.id} href={`#${item.id}`} onClick={closeMenu}>{item.label}</a>)}<button className="theme-toggle" aria-label={`Switch to ${dark ? 'light' : 'dark'} theme`} onClick={() => setDark(!dark)}>{dark ? '☼' : '☾'}</button></div>
    </nav></header>
    <main id="top">
      <section className="hero section-grid" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Verified facts · thoughtful placeholders</p><h1 id="hero-title">Engineering <em>intelligence</em><br />without the invention.</h1><p className="lede">{siteConfig.intro}</p><div className="hero-actions"><a className="button primary" href="#work">Explore work <span>↓</span></a><a className="text-link" href="#contact">Contact <span>↗</span></a></div></div><div className="hero-orbit" aria-label="Backend, content, cloud and AI focus diagram"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit-core">EI<span>+</span></div><div className="orbit-node node-a">CLOUD</div><div className="orbit-node node-b">CONTENT</div><div className="orbit-node node-c">AI</div></div></section>
      <section className="signal-bar" aria-label="Verified focus areas"><span>Focus areas</span><strong>.NET / C#</strong><b>·</b><strong>Azure Functions</strong><b>·</b><strong>Contentful</strong><b>·</b><strong>Event-driven services</strong></section>
      <section id="work" className="content-section" aria-labelledby="work-title"><div className="section-heading"><div><p className="eyebrow">01 / Selected work</p><h2 id="work-title">Named work.<br /><em>Honest detail.</em></h2></div><p className="section-note">Projects use only verified types. Replace bracketed text in the central config with facts before publishing.</p></div><div className="project-list">{siteConfig.projects.slice(0, visibleProjects).map((project, i) => <article className="project-card" key={project.title}><div className="project-number">0{i + 1}</div><div className="project-main"><p className="tag">{project.label}</p><h3>{project.title}</h3><span className="project-type">{project.type ?? 'Type to verify'}</span><p>{project.summary}</p><button className="case-link" onClick={() => setSelected(project)}>Open case study <span>↗</span></button></div><div className="project-impact"><span>Technologies</span><div className="stack">{project.technologies.map((tech) => <small key={tech}>{tech}</small>)}</div></div></article>)}</div>{visibleProjects < siteConfig.projects.length && <button className="view-more" onClick={() => setVisibleProjects(siteConfig.projects.length)}>View more projects <span>↓</span></button>}</section>
      <section id="skills" className="content-section about-grid" aria-labelledby="skills-title"><div><p className="eyebrow">02 / About & skills</p><h2 id="skills-title">Capabilities with<br /><em>evidence labels.</em></h2><div className="about-facts"><p className="case-label">About</p>{siteConfig.about.map((fact) => <p key={fact}>{fact}</p>)}</div></div><div><div className="filter-tabs" role="tablist" aria-label="Filter skills">{categories.map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)} role="tab" aria-selected={category === item}>{item}</button>)}</div><div className="skills-grid">{skills.map((skill) => <article className="skill-card" key={skill.name}><span className="skill-icon">{skill.category === 'AI/automation' ? '✦' : '◈'}</span><div><p className="tag">{skill.category}</p><h3>{skill.name}</h3><p>{skill.detail}</p><small className={`evidence ${skill.evidence.toLowerCase()}`}>{skill.evidence}</small></div></article>)}</div></div></section>
      <section className="content-section ai-cloud-section" aria-labelledby="ai-cloud-title"><div className="section-heading"><div><p className="eyebrow">AI & Cloud</p><h2 id="ai-cloud-title">Separate evidence.<br /><em>Keep exploring.</em></h2></div><p className="section-note">Production facts, proof-of-concepts and exploration are intentionally separated. Replace placeholders with verified evidence.</p></div><div className="ai-cloud-grid">{Object.entries(siteConfig.aiCloud).map(([bucket, entries]) => <article className="ai-cloud-bucket" key={bucket}><span className={`evidence ${bucket.toLowerCase()}`}>{bucket}</span><ul>{entries.map((entry) => <li key={entry}>{entry}</li>)}</ul></article>)}</div></section>
      <section id="approach" className="approach-section" aria-labelledby="approach-title"><div className="section-heading"><div><p className="eyebrow">03 / Approach</p><h2 id="approach-title">Traceable from<br /><em>question to system.</em></h2></div><p className="section-note">Separate what is known from what is a placeholder. Make the boundary clear, then build a useful next step.</p></div><div className="approach-flow"><div><span>01</span><h3>Verify</h3><p>Start with source facts, constraints and the decision that matters.</p></div><div className="flow-arrow">→</div><div><span>02</span><h3>Design</h3><p>Make contracts, boundaries and operational behavior explicit.</p></div><div className="flow-arrow">→</div><div><span>03</span><h3>Learn</h3><p>Ship a bounded slice and document what the evidence says.</p></div></div></section>
      <section className="timeline-section" aria-labelledby="principles-title"><p className="eyebrow">04 / Principles</p><h2 id="principles-title">Clarity is a<br /><em>technical feature.</em></h2><div className="timeline"><div><span>01</span><h3>Evidence over embellishment</h3><p>Claims in this portfolio should be traceable to supplied facts.</p></div><div><span>02</span><h3>Operational boundaries matter</h3><p>Integration, routing, security and processing deserve explicit seams.</p></div></div></section>
      <section id="contact" className="contact-section" aria-labelledby="contact-title"><p className="eyebrow">05 / Contact</p><h2 id="contact-title">Have verified work<br /><em>to share?</em></h2><p>Replace the contact placeholders in <code>src/config.ts</code>, then make this invitation yours.</p><a className="button primary" href={`mailto:${siteConfig.email}`}>Say hello <span>↗</span></a><div className="contact-meta"><span>{siteConfig.location}</span><a href={siteConfig.github}>GitHub ↗</a><a href={siteConfig.linkedin}>LinkedIn ↗</a></div></section>
    </main>
    <footer><span>© 2025 {siteConfig.name}</span><span>Facts first · placeholders visible</span><a href="#top">Back to top ↑</a></footer>
    {selected && <div className="modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && setSelected(null)}><article ref={modalRef} className="modal" role="dialog" tabIndex={-1} aria-modal="true" aria-labelledby="case-title" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close case study">×</button><p className="tag">{selected.label}</p><h2 id="case-title">{selected.title}</h2><p className="project-type">{selected.type ?? 'Type to verify'}</p><div className="case-summary"><div><span className="case-label">Challenge</span><p>{selected.challenge}</p></div><div><span className="case-label">Contribution</span><p>{selected.contribution}</p></div><div><span className="case-label">Outcome</span><p>{selected.outcome}</p></div></div><div className="case-tabs" role="tablist">{selected.tabs.map((tab, i) => <details key={tab.label} open={i === 0}><summary>{tab.label}</summary><p>{tab.content}</p></details>)}</div></article></div>}
  </div>
}
export default App
